#!/bin/bash

#set -x

echo "            "
echo "##### !!! DOWNLOADING FILES !!! #####"
echo "            "
cd /$HOME/Desktop/
git clone https://github.com/lvs1974/ComboJack
cd /$HOME//Desktop/ComboJack/ComboJack_Installer/
./install.sh
echo "Copy VerbStub.kext into your Clover/kext/Other or OC/Kexts"